apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
  labels:
    app: employee-management

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: employee-management

  template:
    metadata:
      labels:
        app: employee-management

    spec:
      containers:
        - name: employee-management
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
