replicaCount: 1

image:
  repository: 172.25.93.123:8083/employee-management
  tag: "1.0"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30630
