spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/employee_management_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sakthi}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sakthi123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true